---
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  applicationDomain: {{ pluck .Values.werf.env .Values.ingress.host | first | default .Values.ingress.host._default }}
  applicationIngressCertificateSecretName: {{ pluck .Values.werf.env .Values.ingress.certificate_secret | first | default .Values.ingress.certificate_secret._default }}
  applicationIngressClassName: "nginx"
