python_api:
  command:
    _default:
    - gunicorn
  args:
    _default:
    - --bind
    - 0.0.0.0:$(PORT)
    - manage:app
  port:
    _default: 5000
  alignment_path:
    _default: generate_fig
golang_web:
  command:
    _default:
    - /golang_web
  args:
    _default: []
  port:
    _default: 8090
log_level:
  _default: debug
redis_addr:
  _default: "rfs-redis:26379"
ingress:
  host:
    _default: alignfig.%s.alexmakh.ru
    production: alignfig.alexmakh.ru
  certificate_secret:
    _default: alignfig-tls