name: Deploy to production
on:
  push:
    branches:
    - main
jobs:
  Werf-Converge:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
        env:
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
